root@srv649924:~# docker container ps
CONTAINER ID   IMAGE                                                COMMAND                  CREATED         STATUS                   PORTS                                                                          NAMES
721ec2b13f83   traefik:v3.1                                         "/entrypoint.sh --pr…"   6 minutes ago   Up 3 minutes             0.0.0.0:80->80/tcp, [::]:80->80/tcp, 0.0.0.0:443->443/tcp, [::]:443->443/tcp   traefik
c1fdd4e532f9   facilita/conexao-de-sorte-frontend:latest            "dumb-init -- serve …"   2 hours ago     Up 3 minutes (healthy)   0.0.0.0:3000->3000/tcp, [::]:3000->3000/tcp                                    conexao-frontend
3dcbb32fc262   mysql:8.4                                            "docker-entrypoint.s…"   5 days ago      Up 3 days                0.0.0.0:3306->3306/tcp, [::]:3306->3306/tcp, 33060/tcp                         conexao-mysql
037bafe7e94c   facilita/conexao-de-sorte-backend:30-07-2025-17-01   "dumb-init -- /app/b…"   2 weeks ago     Up 3 minutes (healthy)   8080/tcp                                                                       backend-prod
97ff4c87c716   b5239da13ab0                                         "/bin/prometheus --c…"   5 weeks ago     Up 3 days                0.0.0.0:9090->9090/tcp, [::]:9090->9090/tcp                                    conexao-prometheus
root@srv649924:~# docker start 721ec2b13f83
721ec2b13f83
root@srv649924:~# docker run 721ec2b13f83
Unable to find image '721ec2b13f83:latest' locally
docker: Error response from daemon: pull access denied for 721ec2b13f83, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

Run 'docker run --help' for more information
root@srv649924:~# docker logs 721ec2b13f83
2025-08-17T15:23:30-03:00 INF Traefik version 3.1.7 built on 2024-10-28T10:41:06Z version=3.1.7
2025-08-17T15:23:30-03:00 INF
Stats collection is disabled.
Help us improve Traefik by turning this feature on :)
More details on: https://doc.traefik.io/traefik/contributing/data-collection/

2025-08-17T15:23:30-03:00 INF Starting provider aggregator aggregator.ProviderAggregator
2025-08-17T15:23:30-03:00 INF Starting provider *file.Provider
2025-08-17T15:23:30-03:00 INF Starting provider *traefik.Provider
2025-08-17T15:23:30-03:00 INF Starting provider *docker.Provider
2025-08-17T15:23:30-03:00 INF Starting provider *acme.Provider
2025-08-17T15:23:30-03:00 INF Testing certificate renew... acmeCA=https://acme-v02.api.letsencrypt.org/directory providerName=letsencrypt.acme
2025-08-17T15:23:30-03:00 INF Starting provider *acme.ChallengeTLSALPN
2025-08-17T15:23:30-03:00 ERR error="error while adding rule (Host(`conexaodesorte.com.br`) || Host(`www.conexaodesorte.com.br`)) && PathPrefix(`/v1/publico`, `/v1/resultados/publico`, `/v1/horario/publico`, `/v1/usuarios/publico`, `/v1/info`): error while adding rule PathPrefix: unexpected number of parameters; got 5, expected one of [1]" entryPointName=websecure routerName=backend-prod-public-https@docker
2025-08-17T15:23:30-03:00 ERR error="open /secrets/traefik-basicauth: no such file or directory" entryPointName=websecure routerName=dashboard@docker
2025-08-17T15:23:33-03:00 INF Register... providerName=letsencrypt.acme
2025-08-17T15:23:35-03:00 ERR Unable to obtain ACME certificate for domains error="unable to generate a certificate for the domains [conexaodesorte.com.br www.conexaodesorte.com.br]: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: too many certificates (5) already issued for this exact set of identifiers in the last 168h0m0s, retry after 2025-08-18 23:16:23 UTC: see https://letsencrypt.org/docs/rate-limits/#new-certificates-per-exact-set-of-identifiers" ACME CA=https://acme-v02.api.letsencrypt.org/directory acmeCA=https://acme-v02.api.letsencrypt.org/directory domains=["conexaodesorte.com.br","www.conexaodesorte.com.br"] providerName=letsencrypt.acme routerName=backend-prod-public-https@docker rule="(Host(`conexaodesorte.com.br`) || Host(`www.conexaodesorte.com.br`)) && PathPrefix(`/v1/publico`, `/v1/resultados/publico`, `/v1/horario/publico`, `/v1/usuarios/publico`, `/v1/info`)"
2025-08-17T15:23:39-03:00 ERR Unable to obtain ACME certificate for domains error="unable to generate a certificate for the domains [traefik.conexaodesorte.com.br]: error: one or more domains had a problem:\n[traefik.conexaodesorte.com.br] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for traefik.conexaodesorte.com.br - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for traefik.conexaodesorte.com.br - check that a DNS record exists for this domain\n" ACME CA=https://acme-v02.api.letsencrypt.org/directory acmeCA=https://acme-v02.api.letsencrypt.org/directory domains=["traefik.conexaodesorte.com.br"] providerName=letsencrypt.acme routerName=dashboard@docker rule=Host(`traefik.conexaodesorte.com.br`)
2025-08-17T15:24:16-03:00 ERR Cannot retrieve the ACME challenge for www.conexaodesorte.com.br (token "RqlISP3ACqX8lwl1NP7XuJBJ1JEVS_vW4Cc9duJn21g") providerName=acme
2025-08-17T15:25:17-03:00 ERR error="open /secrets/traefik-basicauth: no such file or directory" entryPointName=websecure routerName=dashboard@docker
2025-08-17T15:25:25-03:00 ERR Unable to obtain ACME certificate for domains error="unable to generate a certificate for the domains [traefik.conexaodesorte.com.br]: error: one or more domains had a problem:\n[traefik.conexaodesorte.com.br] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for traefik.conexaodesorte.com.br - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for traefik.conexaodesorte.com.br - check that a DNS record exists for this domain\n" ACME CA=https://acme-v02.api.letsencrypt.org/directory acmeCA=https://acme-v02.api.letsencrypt.org/directory domains=["traefik.conexaodesorte.com.br"] providerName=letsencrypt.acme routerName=dashboard@docker rule=Host(`traefik.conexaodesorte.com.br`)
2025-08-17T15:25:43-03:00 INF I have to go...
2025-08-17T15:25:43-03:00 INF Stopping server gracefully
2025-08-17T15:25:43-03:00 ERR error="accept tcp [::]:443: use of closed network connection" entryPointName=websecure
2025-08-17T15:25:43-03:00 ERR Error while starting server error="accept tcp [::]:443: use of closed network connection" entryPointName=websecure
2025-08-17T15:25:43-03:00 ERR error="accept tcp [::]:80: use of closed network connection" entryPointName=web
2025-08-17T15:25:43-03:00 ERR error="close tcp [::]:80: use of closed network connection" entryPointName=web
2025-08-17T15:25:43-03:00 INF Server stopped
2025-08-17T15:25:43-03:00 INF Shutting down
2025-08-17T15:25:54-03:00 INF Traefik version 3.1.7 built on 2024-10-28T10:41:06Z version=3.1.7
2025-08-17T15:25:54-03:00 INF
Stats collection is disabled.
Help us improve Traefik by turning this feature on :)
More details on: https://doc.traefik.io/traefik/contributing/data-collection/

2025-08-17T15:25:54-03:00 INF Starting provider aggregator aggregator.ProviderAggregator
2025-08-17T15:25:54-03:00 INF Starting provider *file.Provider
2025-08-17T15:25:54-03:00 INF Starting provider *traefik.Provider
2025-08-17T15:25:54-03:00 INF Starting provider *docker.Provider
2025-08-17T15:25:54-03:00 INF Starting provider *acme.Provider
2025-08-17T15:25:54-03:00 INF Testing certificate renew... acmeCA=https://acme-v02.api.letsencrypt.org/directory providerName=letsencrypt.acme
2025-08-17T15:25:54-03:00 INF Starting provider *acme.ChallengeTLSALPN
2025-08-17T15:25:55-03:00 ERR error="open /secrets/traefik-basicauth: no such file or directory" entryPointName=websecure routerName=dashboard@docker
2025-08-17T15:26:02-03:00 ERR Unable to obtain ACME certificate for domains error="unable to generate a certificate for the domains [traefik.conexaodesorte.com.br]: error: one or more domains had a problem:\n[traefik.conexaodesorte.com.br] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for traefik.conexaodesorte.com.br - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for traefik.conexaodesorte.com.br - check that a DNS record exists for this domain\n" ACME CA=https://acme-v02.api.letsencrypt.org/directory acmeCA=https://acme-v02.api.letsencrypt.org/directory domains=["traefik.conexaodesorte.com.br"] providerName=letsencrypt.acme routerName=dashboard@docker rule=Host(`traefik.conexaodesorte.com.br`)
2025-08-17T15:27:30-03:00 ERR error="open /secrets/traefik-basicauth: no such file or directory" entryPointName=websecure routerName=dashboard@docker
2025-08-17T15:27:30-03:00 ERR error="error while adding rule (Host(`conexaodesorte.com.br`) || Host(`www.conexaodesorte.com.br`)) && PathPrefix(`/v1/publico`, `/v1/resultados/publico`, `/v1/horario/publico`, `/v1/usuarios/publico`, `/v1/info`): error while adding rule PathPrefix: unexpected number of parameters; got 5, expected one of [1]" entryPointName=websecure routerName=backend-prod-public-https@docker
2025-08-17T15:27:30-03:00 ERR Unable to obtain ACME certificate for domains error="unable to generate a certificate for the domains [conexaodesorte.com.br www.conexaodesorte.com.br]: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: too many certificates (5) already issued for this exact set of identifiers in the last 168h0m0s, retry after 2025-08-18 23:30:56 UTC: see https://letsencrypt.org/docs/rate-limits/#new-certificates-per-exact-set-of-identifiers" ACME CA=https://acme-v02.api.letsencrypt.org/directory acmeCA=https://acme-v02.api.letsencrypt.org/directory domains=["conexaodesorte.com.br","www.conexaodesorte.com.br"] providerName=letsencrypt.acme routerName=backend-prod-https@docker rule="(Host(`conexaodesorte.com.br`) || Host(`www.conexaodesorte.com.br`)) && PathPrefix(`/rest`)"
2025-08-17T15:27:35-03:00 ERR Unable to obtain ACME certificate for domains error="unable to generate a certificate for the domains [traefik.conexaodesorte.com.br]: error: one or more domains had a problem:\n[traefik.conexaodesorte.com.br] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for traefik.conexaodesorte.com.br - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for traefik.conexaodesorte.com.br - check that a DNS record exists for this domain\n" ACME CA=https://acme-v02.api.letsencrypt.org/directory acmeCA=https://acme-v02.api.letsencrypt.org/directory domains=["traefik.conexaodesorte.com.br"] providerName=letsencrypt.acme routerName=dashboard@docker rule=Host(`traefik.conexaodesorte.com.br`)
root@srv649924:~# docker stop 721ec2b13f83
721ec2b13f83
root@srv649924:~# docker run 721ec2b13f83
Unable to find image '721ec2b13f83:latest' locally
docker: Error response from daemon: pull access denied for 721ec2b13f83, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

Run 'docker run --help' for more information
root@srv649924:~# docker start 721ec2b13f83
721ec2b13f83
root@srv649924:~# docker logs 721ec2b13f83
2025-08-17T15:23:30-03:00 INF Traefik version 3.1.7 built on 2024-10-28T10:41:06Z version=3.1.7
2025-08-17T15:23:30-03:00 INF
Stats collection is disabled.
Help us improve Traefik by turning this feature on :)
More details on: https://doc.traefik.io/traefik/contributing/data-collection/

2025-08-17T15:23:30-03:00 INF Starting provider aggregator aggregator.ProviderAggregator
2025-08-17T15:23:30-03:00 INF Starting provider *file.Provider
2025-08-17T15:23:30-03:00 INF Starting provider *traefik.Provider
2025-08-17T15:23:30-03:00 INF Starting provider *docker.Provider
2025-08-17T15:23:30-03:00 INF Starting provider *acme.Provider
2025-08-17T15:23:30-03:00 INF Testing certificate renew... acmeCA=https://acme-v02.api.letsencrypt.org/directory providerName=letsencrypt.acme
2025-08-17T15:23:30-03:00 INF Starting provider *acme.ChallengeTLSALPN
2025-08-17T15:23:30-03:00 ERR error="error while adding rule (Host(`conexaodesorte.com.br`) || Host(`www.conexaodesorte.com.br`)) && PathPrefix(`/v1/publico`, `/v1/resultados/publico`, `/v1/horario/publico`, `/v1/usuarios/publico`, `/v1/info`): error while adding rule PathPrefix: unexpected number of parameters; got 5, expected one of [1]" entryPointName=websecure routerName=backend-prod-public-https@docker
2025-08-17T15:23:30-03:00 ERR error="open /secrets/traefik-basicauth: no such file or directory" entryPointName=websecure routerName=dashboard@docker
2025-08-17T15:23:33-03:00 INF Register... providerName=letsencrypt.acme
2025-08-17T15:23:35-03:00 ERR Unable to obtain ACME certificate for domains error="unable to generate a certificate for the domains [conexaodesorte.com.br www.conexaodesorte.com.br]: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: too many certificates (5) already issued for this exact set of identifiers in the last 168h0m0s, retry after 2025-08-18 23:16:23 UTC: see https://letsencrypt.org/docs/rate-limits/#new-certificates-per-exact-set-of-identifiers" ACME CA=https://acme-v02.api.letsencrypt.org/directory acmeCA=https://acme-v02.api.letsencrypt.org/directory domains=["conexaodesorte.com.br","www.conexaodesorte.com.br"] providerName=letsencrypt.acme routerName=backend-prod-public-https@docker rule="(Host(`conexaodesorte.com.br`) || Host(`www.conexaodesorte.com.br`)) && PathPrefix(`/v1/publico`, `/v1/resultados/publico`, `/v1/horario/publico`, `/v1/usuarios/publico`, `/v1/info`)"
2025-08-17T15:23:39-03:00 ERR Unable to obtain ACME certificate for domains error="unable to generate a certificate for the domains [traefik.conexaodesorte.com.br]: error: one or more domains had a problem:\n[traefik.conexaodesorte.com.br] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for traefik.conexaodesorte.com.br - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for traefik.conexaodesorte.com.br - check that a DNS record exists for this domain\n" ACME CA=https://acme-v02.api.letsencrypt.org/directory acmeCA=https://acme-v02.api.letsencrypt.org/directory domains=["traefik.conexaodesorte.com.br"] providerName=letsencrypt.acme routerName=dashboard@docker rule=Host(`traefik.conexaodesorte.com.br`)
2025-08-17T15:24:16-03:00 ERR Cannot retrieve the ACME challenge for www.conexaodesorte.com.br (token "RqlISP3ACqX8lwl1NP7XuJBJ1JEVS_vW4Cc9duJn21g") providerName=acme
2025-08-17T15:25:17-03:00 ERR error="open /secrets/traefik-basicauth: no such file or directory" entryPointName=websecure routerName=dashboard@docker
2025-08-17T15:25:25-03:00 ERR Unable to obtain ACME certificate for domains error="unable to generate a certificate for the domains [traefik.conexaodesorte.com.br]: error: one or more domains had a problem:\n[traefik.conexaodesorte.com.br] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for traefik.conexaodesorte.com.br - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for traefik.conexaodesorte.com.br - check that a DNS record exists for this domain\n" ACME CA=https://acme-v02.api.letsencrypt.org/directory acmeCA=https://acme-v02.api.letsencrypt.org/directory domains=["traefik.conexaodesorte.com.br"] providerName=letsencrypt.acme routerName=dashboard@docker rule=Host(`traefik.conexaodesorte.com.br`)
2025-08-17T15:25:43-03:00 INF I have to go...
2025-08-17T15:25:43-03:00 INF Stopping server gracefully
2025-08-17T15:25:43-03:00 ERR error="accept tcp [::]:443: use of closed network connection" entryPointName=websecure
2025-08-17T15:25:43-03:00 ERR Error while starting server error="accept tcp [::]:443: use of closed network connection" entryPointName=websecure
2025-08-17T15:25:43-03:00 ERR error="accept tcp [::]:80: use of closed network connection" entryPointName=web
2025-08-17T15:25:43-03:00 ERR error="close tcp [::]:80: use of closed network connection" entryPointName=web
2025-08-17T15:25:43-03:00 INF Server stopped
2025-08-17T15:25:43-03:00 INF Shutting down
2025-08-17T15:25:54-03:00 INF Traefik version 3.1.7 built on 2024-10-28T10:41:06Z version=3.1.7
2025-08-17T15:25:54-03:00 INF
Stats collection is disabled.
Help us improve Traefik by turning this feature on :)
More details on: https://doc.traefik.io/traefik/contributing/data-collection/

2025-08-17T15:25:54-03:00 INF Starting provider aggregator aggregator.ProviderAggregator
2025-08-17T15:25:54-03:00 INF Starting provider *file.Provider
2025-08-17T15:25:54-03:00 INF Starting provider *traefik.Provider
2025-08-17T15:25:54-03:00 INF Starting provider *docker.Provider
2025-08-17T15:25:54-03:00 INF Starting provider *acme.Provider
2025-08-17T15:25:54-03:00 INF Testing certificate renew... acmeCA=https://acme-v02.api.letsencrypt.org/directory providerName=letsencrypt.acme
2025-08-17T15:25:54-03:00 INF Starting provider *acme.ChallengeTLSALPN
2025-08-17T15:25:55-03:00 ERR error="open /secrets/traefik-basicauth: no such file or directory" entryPointName=websecure routerName=dashboard@docker
2025-08-17T15:26:02-03:00 ERR Unable to obtain ACME certificate for domains error="unable to generate a certificate for the domains [traefik.conexaodesorte.com.br]: error: one or more domains had a problem:\n[traefik.conexaodesorte.com.br] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for traefik.conexaodesorte.com.br - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for traefik.conexaodesorte.com.br - check that a DNS record exists for this domain\n" ACME CA=https://acme-v02.api.letsencrypt.org/directory acmeCA=https://acme-v02.api.letsencrypt.org/directory domains=["traefik.conexaodesorte.com.br"] providerName=letsencrypt.acme routerName=dashboard@docker rule=Host(`traefik.conexaodesorte.com.br`)
2025-08-17T15:27:30-03:00 ERR error="open /secrets/traefik-basicauth: no such file or directory" entryPointName=websecure routerName=dashboard@docker
2025-08-17T15:27:30-03:00 ERR error="error while adding rule (Host(`conexaodesorte.com.br`) || Host(`www.conexaodesorte.com.br`)) && PathPrefix(`/v1/publico`, `/v1/resultados/publico`, `/v1/horario/publico`, `/v1/usuarios/publico`, `/v1/info`): error while adding rule PathPrefix: unexpected number of parameters; got 5, expected one of [1]" entryPointName=websecure routerName=backend-prod-public-https@docker
2025-08-17T15:27:30-03:00 ERR Unable to obtain ACME certificate for domains error="unable to generate a certificate for the domains [conexaodesorte.com.br www.conexaodesorte.com.br]: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: too many certificates (5) already issued for this exact set of identifiers in the last 168h0m0s, retry after 2025-08-18 23:30:56 UTC: see https://letsencrypt.org/docs/rate-limits/#new-certificates-per-exact-set-of-identifiers" ACME CA=https://acme-v02.api.letsencrypt.org/directory acmeCA=https://acme-v02.api.letsencrypt.org/directory domains=["conexaodesorte.com.br","www.conexaodesorte.com.br"] providerName=letsencrypt.acme routerName=backend-prod-https@docker rule="(Host(`conexaodesorte.com.br`) || Host(`www.conexaodesorte.com.br`)) && PathPrefix(`/rest`)"
2025-08-17T15:27:35-03:00 ERR Unable to obtain ACME certificate for domains error="unable to generate a certificate for the domains [traefik.conexaodesorte.com.br]: error: one or more domains had a problem:\n[traefik.conexaodesorte.com.br] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up A for traefik.conexaodesorte.com.br - check that a DNS record exists for this domain; DNS problem: NXDOMAIN looking up AAAA for traefik.conexaodesorte.com.br - check that a DNS record exists for this domain\n" ACME CA=https://acme-v02.api.letsencrypt.org/directory acmeCA=https://acme-v02.api.letsencrypt.org/directory domains=["traefik.conexaodesorte.com.br"] providerName=letsencrypt.acme routerName=dashboard@docker rule=Host(`traefik.conexaodesorte.com.br`)
2025-08-17T15:30:36-03:00 INF I have to go...
2025-08-17T15:30:36-03:00 INF Stopping server gracefully
2025-08-17T15:30:36-03:00 ERR error="accept tcp [::]:80: use of closed network connection" entryPointName=web
2025-08-17T15:30:36-03:00 ERR Error while starting server error="accept tcp [::]:80: use of closed network connection" entryPointName=web
2025-08-17T15:30:36-03:00 ERR error="accept tcp [::]:443: use of closed network connection" entryPointName=websecure
2025-08-17T15:30:36-03:00 ERR error="close tcp [::]:443: use of closed network connection" entryPointName=websecure
2025-08-17T15:30:36-03:00 INF Server stopped
2025-08-17T15:30:36-03:00 INF Shutting down
2025-08-17T15:30:52-03:00 INF Traefik version 3.1.7 built on 2024-10-28T10:41:06Z version=3.1.7
2025-08-17T15:30:52-03:00 INF
Stats collection is disabled.
Help us improve Traefik by turning this feature on :)
More details on: https://doc.traefik.io/traefik/contributing/data-collection/

2025-08-17T15:30:52-03:00 INF Starting provider aggregator aggregator.ProviderAggregator
2025-08-17T15:30:52-03:00 INF Starting provider *file.Provider
2025-08-17T15:30:52-03:00 INF Starting provider *traefik.Provider
2025-08-17T15:30:52-03:00 INF Starting provider *docker.Provider
2025-08-17T15:30:52-03:00 INF Starting provider *acme.ChallengeTLSALPN
2025-08-17T15:30:52-03:00 INF Starting provider *acme.Provider
2025-08-17T15:30:52-03:00 INF Testing certificate renew... acmeCA=https://acme-v02.api.letsencrypt.org/directory providerName=letsencrypt.acme
2025-08-17T15:30:52-03:00 ERR error="open /secrets/traefik-basicauth: no such file or directory" entryPointName=websecure routerName=dashboard@docker
2025-08-17T15:30:52-03:00 ERR error="error while adding rule (Host(`conexaodesorte.com.br`) || Host(`www.conexaodesorte.com.br`)) && PathPrefix(`/v1/publico`, `/v1/resultados/publico`, `/v1/horario/publico`, `/v1/usuarios/publico`, `/v1/info`): error while adding rule PathPrefix: unexpected number of parameters; got 5, expected one of [1]" entryPointName=websecure routerName=backend-prod-public-https@docker
2025-08-17T15:30:53-03:00 ERR Unable to obtain ACME certificate for domains error="unable to generate a certificate for the domains [conexaodesorte.com.br www.conexaodesorte.com.br]: acme: error: 429 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rateLimited :: too many certificates (5) already issued for this exact set of identifiers in the last 168h0m0s, retry after 2025-08-18 23:12:30 UTC: see https://letsencrypt.org/docs/rate-limits/#new-certificates-per-exact-set-of-identifiers" ACME CA=https://acme-v02.api.letsencrypt.org/directory acmeCA=https://acme-v02.api.letsencrypt.org/directory domains=["conexaodesorte.com.br","www.conexaodesorte.com.br"] providerName=letsencrypt.acme routerName=backend-prod-https@docker rule="(Host(`conexaodesorte.com.br`) || Host(`www.conexaodesorte.com.br`)) && PathPrefix(`/rest`)"